title: 'lovata.shopaholic::lang.title.brand_list'
modelClass: Lovata\Shopaholic\Models\Brand
list: $/lovata/shopaholic/models/brand/columns.yaml
recordUrl: 'lovata/shopaholic/brands/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '25'
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
    column: sort_order
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: _config_filter.yaml
