name: 'lovata.shopaholic::lang.breadcrumbs.products'
modelClass: Lovata\Shopaholic\Models\Product
form: $/lovata/shopaholic/models/product/fields.yaml
defaultRedirect: lovata/shopaholic/products
create:
    title: 'lovata.shopaholic::lang.title.product_create'
    redirect: 'lovata/shopaholic/products/update/:id'
    redirectClose: lovata/shopaholic/products
    flashSave: 'lovata.shopaholic::lang.message.product_create'
update:
    title: 'lovata.shopaholic::lang.title.product_update'
    redirect: lovata/shopaholic/products
    redirectClose: lovata/shopaholic/products
    flashSave: 'lovata.shopaholic::lang.message.product_update'
    flashDelete: 'lovata.shopaholic::lang.message.product_delete'
preview: {  }
