title: 'lovata.shopaholic::lang.title.product_list'
modelClass: Lovata\Shopaholic\Models\Offer
list: $/lovata/shopaholic/models/offer/columns.yaml
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '25'
showSetup: 1
showCheckboxes: true
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
